services:
  ui:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://127.0.0.1:8000}
    image: adan-pradan-ui:latest
    ports:
      - "3000:3000"
